# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # (see https://crontab.guru)
    - cron: '05 8-17/1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

      # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Beginne Wohnungscheck..

    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version

    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Dheadless=true

    - if: always()
      run: git status

    - name: Commit changes
      if: always()
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'Update hashes'
        add: '*.txt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
